### PR TITLE
Added a media query fix for when the device height is less than 600.

### LINKED ISSUE #742: stop at this step, it will not work!
//[

Image

](url)

### PR DESCRIPTION
**Pull request by Josephus-git**
closes #742 
fixed rendering issue on create wallet button for small devices 
Screenshot from 2025-08-24 22-37-51

### CODE REVIEW

File: ui/page/start_page.go [hunk 1]
```diff
@@ -450,8 +454,16 @@ func (sp *startPage) loadingSection(gtx C) D {
...
-				inset := layout.Inset{Top: values.MarginPadding100}
-				if sp.IsMobileView() {
+
+				var topMargin unit.Dp
+				if isSmallScreen {
+					topMargin = values.MarginPadding10
+				} else {
+					topMargin = values.MarginPadding100
+				}
+				inset := layout.Inset{Top: topMargin}
```
Comment (dreacot) [inline ui/page/start_page.go:464]:
```suggestion
				topMargin := values.MarginPadding100
				if isSmallScreen {
					topMargin = values.MarginPadding10
				}
				inset := layout.Inset{Top: topMargin}
```

Try to avoid if else statements where possible as it makes the code messy. the above is shorter and easier to read

**Review by dreacot — CHANGES_REQUESTED** [review]
