### PR TITLE
fix bugs and improve code

### LINKED ISSUE #234: create-order-page: "Create Wallet" modal no longer  redirects to the create wallet page
The "Create Wallet" modal no longer redirects to the "create wallet" page when "Continue" is clicked.

Screenshot 2023-11-03 at 8 14 20 PM

### LINKED ISSUE #375: clicking on proposals from the overview page causes the app to crash
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x101b0bb3c]

goroutine 219 [running]:
github.com/crypto-power/cryptopower/libwallet/internal/politeia.(*Politeia).FetchProposalDescription(0x14000180d20, {0x1400358bfa0, 0x10})
        /Users/user/go/src/github.com/crypto-power/cryptopower/libwallet/internal/politeia/politeia_sync.go:371 +0x4c
github.com/crypto-power/cryptopower/ui/page/governance.(*ProposalDetails).loadProposalDescription.func1()
        /Users/user/go/src/github.com/crypto-power/cryptopower/ui/page/governance/proposal_details_page.go:145 +0x90
created by github.com/crypto-power/cryptopower/ui/page/governance.(*ProposalDetails).loadProposalDescription in goroutine 43
        /Users/user/go/src/github.com/crypto-power/cryptopower/ui/page/governance/proposal_details_page.go:139 +0x74
exit status 2
```

### PR DESCRIPTION
**Pull request by dreacot**
- [x] add appicon.png (used to generate icons while building for android/ios)
- [x] Fixed a bug where the CEX welcome page was always showing 
- [x] Fixed a crash that occurred when clicking on proposals from the overview page (closes #375)
- [x] Allow users to starts sync when they see the error message that states page is unavailable until sync has started, and also show the sync progress on the pages after it is started (reported in #367 )
- [x] Allow users create a wallet from the CEX page when overlay when it says multiple wallet types are required
- [x] Fixed a bug where the create wallet modal no longer works on the cex page (closes #234)
- [x] Centralize the empty text of the recent tx and recent staking activities
- [x] Add info icons to the wallet setup page during onboarding to explain what the advanced/recommended setting does (as part of #367 )

### CODE REVIEW

File: libwallet/internal/politeia/politeia_sync.go [hunk 1]
```diff
@@ -363,6 +363,10 @@ func (p *Politeia) fetchBatchProposals(category int32, tokens []string, broadcas
 
 func (p *Politeia) FetchProposalDescription(token string) (string, error) {
 	// Check if politeia has been shutdown and exit if true.
```
Comment (ukane-philemon) [inline libwallet/internal/politeia/politeia_sync.go:365]: I think this should mv to L369

File: main/main.go
Comment (ukane-philemon) [inline main/main.go:1]: Erm, this does not belong here, I think.

File: ui/page/exchange/create_order_page.go [hunk 2]
```diff
@@ -255,7 +257,7 @@ func (pg *CreateOrderPage) displayCreateWalletModal(isSourceWallet bool, asset l
 		SetCancelable(true).
 		SetContentAlignment(layout.Center, layout.W, layout.Center).
 		SetPositiveButtonCallback(func(_ bool, _ *modal.InfoModal) bool {
-			pg.ParentNavigator().Display(components.NewCreateWallet(pg.Load, func() {
+			pg.ParentWindow().Display(components.NewCreateWallet(pg.Load, func() {
```
Comment (ukane-philemon) [inline ui/page/exchange/create_order_page.go:260]: Errm, #389. I think it's consistent to show the form on the same master page as the create order page

File: ui/page/exchange/create_order_page.go [hunk 3]
```diff
@@ -266,13 +268,13 @@ func (pg *CreateOrderPage) displayCreateWalletModal(isSourceWallet bool, asset l
 }
 
 func (pg *CreateOrderPage) walletCreationSuccessFunc(isSourceWallet bool, asset libutils.AssetType) {
+	pg.OnNavigatedTo()
```
Comment (ukane-philemon) [inline ui/page/exchange/create_order_page.go:271]: Any reason why we are doing this?

File: ui/page/exchange/create_order_page.go [hunk 4]
```diff
@@ -266,13 +268,13 @@ func (pg *CreateOrderPage) displayCreateWalletModal(isSourceWallet bool, asset l
...
 	if isSourceWallet {
 		pg.updateWalletAndAccountSelector([]libutils.AssetType{asset}, nil)
 	} else {
 		pg.updateWalletAndAccountSelector(nil, []libutils.AssetType{asset})
 	}
-	pg.ParentNavigator().ClosePagesAfter(CreateOrderPageID)
-	pg.ParentNavigator().ClosePagesAfter(CreateOrderPageID)
+	pg.ParentWindow().CloseCurrentPage()
```
Comment (ukane-philemon) [inline ui/page/exchange/create_order_page.go:277]: See my comment before the one above.

File: ui/page/exchange/create_order_page.go [hunk 5]
```diff
@@ -1448,3 +1459,29 @@ func (pg *CreateOrderPage) fetchInstantExchangeCurrencies() error {
...
+				break
+			}
+		}
+
+		if !assetExists {
+			assetsNotCreated = append(assetsNotCreated, asset)
+		}
+	}
+
+	return assetsNotCreated[0]
```
Comment (ukane-philemon) [inline ui/page/exchange/create_order_page.go:1486]: I think we should check the `len`? better safe than sorry.

**Review by ukane-philemon — CHANGES_REQUESTED** [review]
Nice work! Just a few things that caught my attention.

File: ui/page/exchange/create_order_page.go (hunk 3 above)
Comment (dreacot) [reply ui/page/exchange/create_order_page.go:271]: yeah creating a wallet from the initial disabled page needs the create order page to be reinitialised

File: ui/page/exchange/create_order_page.go (hunk 5 above)
Comment (dreacot) [reply ui/page/exchange/create_order_page.go:1486]: if len is not greater than zero then we would gave to return nil, which still panics

before this method can be called initially it means the app only has one asset created only, so this would always return a value

Comment (ukane-philemon) [reply ui/page/exchange/create_order_page.go:1486]: ok

File: ui/page/settings/help_page.go [hunk 6]
```diff
@@ -120,47 +178,51 @@ func (pg *HelpPage) pageHeaderLayout(gtx layout.Context) layout.Dimensions {
 	)
 }
 
-func (pg *HelpPage) pageContentLayout(gtx layout.Context) layout.Dimensions {
-	gtx.Constraints.Min.X = gtx.Constraints.Max.X
-	return layout.Center.Layout(gtx, func(gtx layout.Context) layout.Dimensions {
-		gtx.Constraints.Min.X = gtx.Dp(values.MarginPadding550)
-		gtx.Constraints.Max.X = gtx.Constraints.Min.X
+func (pg *HelpPage) pageContentLayout(gtx layout.Context) layout.FlexChild {
```
Comment (ukane-philemon) [inline ui/page/settings/help_page.go:181]: `gtx` is unused?

**Review by ukane-philemon — APPROVED** [review]
Looks straightforward. Just a nit.

PS: PR is failing CI run (should be lint err).

File: ui/page/settings/help_page.go (hunk 6 above)
Comment (dreacot) [reply ui/page/settings/help_page.go]: fixed

**Review by ukane-philemon — APPROVED** [review]
