### PR TITLE
UI layout clean up and bug fix

### LINKED ISSUE #67: pending UI improvements
1. the create order page isn't centralised while in full screen mode

image

2. this whole section should move to the trade tab

image

3. the create order page isn't fully visible while in normal widow size, it needs a scroll bar

image

4. there's a gap between the gradient and the tab above it, it should go
5. also the side nav isn't fully accessible 

image

### PR DESCRIPTION
**Pull request by Sirmorrison**
fix #67 

This PR resolves all the issues listed in issue 67
* move dex, trade pages to trade tab
* fix excess padding between top navigation and page content layout
* fix hidden side nav buttons
* fix order page content alignment bug
* add total value info modal etc

image

### CODE REVIEW

File: ui/page/root/wallet_selector_page.go [hunk 1]
```diff
@@ -16,11 +16,10 @@ import (
 	"github.com/crypto-power/cryptopower/ui/load"
 	"github.com/crypto-power/cryptopower/ui/modal"
 	"github.com/crypto-power/cryptopower/ui/page/components"
-	"github.com/crypto-power/cryptopower/ui/page/exchange"
 	"github.com/crypto-power/cryptopower/ui/values"
 )
 
-const WalletDexServerSelectorID = "wallet_dex_server_selector"
+const WalletSelectorPageID = "wallet__selector"
```
Comment (dreacot) [inline ui/page/root/wallet_selector_page.go:22]: why does this have double underscore

**Comment by dmigwi** [comment]
Apart from the few UI designs issue I have raised, the code looks good to me!

**Review by dreacot — APPROVED** [review]
