### PR TITLE
btc/ltc: Do not use chain client notifications.

### LINKED ISSUE #487: dextest: btc transactions do not get confirms.
This is specifically for the network `--network=dextest`, btc transactions never get confirms. I suspect I missed something when adding it to do with the network.

I also was able to hit a panic, unsure if it's connected but recording here anyhow:
```
2024-03-20 14:21:09.938 [INF] BTC: Inserting unconfirmed transaction 479a2d1c21ae6ed2bed68c320a34d19c76d89b5c6da5d9ffe0fe7c42ec288643
2024-03-20 14:21:19.112 [INF] BTC: Current sync progress update is on block 675, target sync block is 675
2024-03-20 14:21:34.120 [INF] BTC: Current sync progress update is on block 676, target sync block is 676
2024-03-20 14:21:49.130 [INF] BTC: Current sync progress update is on block 677, target sync block is 677
2024-03-20 14:22:04.141 [INF] BTC: Current sync progress update is on block 678, target sync block is 678
2024-03-20 14:22:09.947 [INF] BTC: Inserting unconfirmed transaction 7f25ce701576de78b34d57806c403fb2a49b67dfebed6a273344bd9fe06c6569
2024-03-20 14:22:19.150 [INF] BTC: Current sync progress update is on block 679, target sync block is 679
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x12291d6]

goroutine 27 [running]:
github.com/crypto-power/cryptopower/libwallet/assets/btc.(*Asset).lockedAmount(0xc0030a5320)
        /home/joe/git/cryptopower/libwallet/assets/btc/accounts.go:136 +0x36
github.com/crypto-power/cryptopower/libwallet/assets/btc.(*Asset).GetAccountBalance(0xc0030a5320, 0x0)
        /home/joe/git/cryptopower/libwallet/assets/btc/accounts.go:113 +0x8a
github.com/crypto-power/cryptopower/libwallet/assets/btc.(*Asset).GetAccountsRaw(0xc0030a5320)
        /home/joe/git/cryptopower/libwallet/assets/btc/accounts.go:57 +0x125
github.com/crypto-power/cryptopower/libwallet.(*AssetsManager).CalculateTotalAssetsBalance(0xc002cd89a0, 0x1)
        /home/joe/git/cryptopower/libwallet/assets_manager.go:808 +0xc6
github.com/crypto-power/cryptopower/ui/page/root.(*HomePage).CalculateAssetsUSDBalance(0xc00381e340)
        /home/joe/git/cryptopower/ui/page/root/home_page.go:1047 +0x5a
github.com/crypto-power/cryptopower/libwallet/ext.(*CommonRateSource).notifyRateListeners(0xc0030a5560?)
        /home/joe/git/cryptopower/libwallet/ext/rate_source.go:480 +0xe2
github.com/crypto-power/cryptopower/libwallet/ext.(*CommonRateSource).startWebsocket.func1()
        /home/joe/git/cryptopower/libwallet/ext/rate_source.go:393 +0xc5
created by github.com/crypto-power/cryptopower/libwallet/ext.(*CommonRateSource).startWebsocket in goroutine 50
        /home/joe/git/cryptopower/libwallet/ext/rate_source.go:346 +0x94
```

### LINKED ISSUE #488: dextest: btc restoration never finishes.
Testing on dextest, so may not be a real problem, but may be.

Unable to restore a wallet on master, it gets stuck in this state:

image

Logs will show this error over and over:
```
2024-03-21 16:26:30.467 [ERR] BTC: Unable to process chain backend block connected notification: failed to store sync information 21f1333c7661fc4906f8153f03fa5c44ab750b68f2e9cd26c5b49fad5f71119b: failed to fetch block hash for height 1422: block not found
2024-03-21 16:26:45.480 [INF] BTC: Current sync progress update is on block 1424, target sync block is 1424
2024-03-21 16:27:00.493 [INF] BTC: Current sync progress update is on block 1425, target sync block is 1425
2024-03-21 16:27:15.504 [ERR] BTC: Unable to process chain backend block connected notification: failed to store sync information 6086127db16f0884c164275b5301aa9c44cd4b6ca3722860f936fe38abe0b502: failed to fetch block hash for height 1425: block not found
2024-03-21 16:27:15.504 [INF] BTC: Current sync progress update is on block 1426, target sync block is 1426

```

### PR DESCRIPTION
**Pull request by JoeGruffins**
Notification from the chain client are only meant for one consumer, and that consumer is btcwallet. Instead receive all notifications from btcwallet.

closes #487, closes #488

### CODE REVIEW

File: libwallet/assets/btc/sync.go [hunk 1]
```diff
@@ -222,114 +217,93 @@ func (asset *Asset) handleSyncUIUpdate() {
 }
 
 func (asset *Asset) handleNotifications() {
-	t := time.NewTicker(syncIntervalGap)
+	t := time.NewTicker(time.Second)
+	defer t.Stop()
+	notes := asset.Internal().BTC.NtfnServer.TransactionNotifications()
```
Comment (JustinBeBoy) [inline libwallet/assets/btc/sync.go:222]: notes is only transaction notifications not all notification for syncing progress, so the progress bar can't update percent for users

File: libwallet/assets/btc/rescan.go [hunk 2]
```diff
@@ -390,28 +389,3 @@ func (asset *Asset) getblockStamp(height int32) (*waddrmgr.BlockStamp, error) {
 		Timestamp: block.Header.Timestamp,
 	}, nil
 }
-
-// updateSyncedToBlock is used to update syncedTo block. Sometimes btcwallet might
-// miss the trigger event to update syncedTo block so the update is done here
-// regardless thus avoid handling the possible scenario where btcwallet might miss
-// the syncedto store trigger event.
-func (asset *Asset) updateSyncedToBlock(height int32) {
```
Comment (JustinBeBoy) [inline libwallet/assets/btc/rescan.go:398]: why remove this function, it need to update progress bar for UI

File: libwallet/assets/ltc/rescan.go [hunk 3]
```diff
@@ -345,28 +344,3 @@ func (asset *Asset) getblockStamp(height int32) (*waddrmgr.BlockStamp, error) {
 		Timestamp: block.Header.Timestamp,
 	}, nil
 }
-
-// updateSyncedToBlock is used to update syncedTo block. Sometimes ltcwallet might
-// miss the trigger event to update syncedTo block so the update is done here
-// regardless thus avoid handling the possible scenario where ltcwallet might miss
-// the syncedto store trigger event.
-func (asset *Asset) updateSyncedToBlock(height int32) {
```
Comment (JustinBeBoy) [inline libwallet/assets/ltc/rescan.go:353]: the same btc

**Review by JustinBeBoy — CHANGES_REQUESTED** [review]
When I test it on dexttest, I get stuck on loading state, but when test it on testnet it work for me, but the progress bar not update percent even though the process is running

image

**Comment by JoeGruffins** [comment]
> When I test it on dexttest, I get stuck on loading state

You must run the dcrdex simnet dcr harness.

I guess I need to send the block updates sometimes even during initial sync.

File: libwallet/assets/btc/sync.go (hunk 1 above)
Comment (JoeGruffins) [reply libwallet/assets/btc/sync.go:222]: I think it can if we just ask btcwallet what its best block is.

We **can't** use the notifications from neutrino is the thing.

File: libwallet/assets/btc/rescan.go (hunk 2 above)
Comment (JoeGruffins) [reply libwallet/assets/btc/rescan.go:398]: I don't think that is what it does. It is there because sometimes btcwallet was not getting the notifications it needed, so this was a bandaid.

**Comment by JoeGruffins** [comment]
Now polling blocks during sync. It looks like we do not get block notifications at all during that time. https://github.com/crypto-power/cryptopower/compare/d15597b7830216c8af9d541c75b1d373af1f5948..01fd0b1dd4870058e9f2dc9a27bad36bc6a77b95

**Comment by dreacot** [comment]
this is my sync log, i see `neutrino rescan ended with error`, but the rest of the log seems to suggest the rescan actually completed

```
2024-04-16 11:51:05.370 [INF] BTC: Fetching block height=2586243 hash=000000000000002067d6e9fb6e770b0ec080e6080c81ef6c76b57b055c1d7705
2024-04-16 11:51:06.623 [INF] BTC: Fetching block height=2586260 hash=0000000000000008b8bfa3636959643411954422e49796ae9b240faa6c690f66
2024-04-16 11:51:07.998 [INF] BTC: Recovered addresses from blocks 2585217-2586535
2024-04-16 11:51:08.042 [INF] BTC: Started rescan from block 000000000000000a0c2542841816965e17341e1d9005a06310ee7aa7acc4322c (height 2586535) for 126 addresses
2024-04-16 11:51:08.043 [ERR] BTC: Neutrino rescan ended with error: rescan exited
2024-04-16 11:51:33.709 [INF] BTC: Catching up block hashes to height 2586535, this might take a while
2024-04-16 11:51:33.709 [INF] BTC: Done catching up block hashes
2024-04-16 11:51:33.709 [INF] BTC: Finished rescan for 126 addresses (synced to block 000000000000000a0c2542841816965e17341e1d9005a06310ee7aa7acc4322c, height 2586535)
```

**Review by dreacot — COMMENTED** [review]
Testing this works well

**Comment by JoeGruffins** [comment]
> 2024-04-16 11:51:08.043 [ERR] BTC: Neutrino rescan ended with error: rescan exited

This is normal. You will also see it on master. It's not an error at all.

**Comment by dreacot** [comment]
okay, please let me know when you double check so i can merge if nothing else blocking

**Comment by JoeGruffins** [comment]
> okay, please let me know when you double check so i can merge if nothing else blocking

https://github.com/lightninglabs/neutrino/pull/234

Nothing we can do here.

**Review by dreacot — APPROVED** [review]
