### PR TITLE
ui: fix panic on create order page

### LINKED ISSUE #183: Panic on create order page
To reproduce:

Start the app, Go to settings and turn off exchange APIs. Go to the trade tab, Click on the Exchange btn that opens up the create order page. You will see a message that says to enable the exchange API to trade. Go back to settings and enable the Exchange APIs. After clicking the back btn on the settings page the create order page will be displayed and the message overlay will be removed. Selecting an asset will crash the app.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x100dd161d]

goroutine 13 [running]:
github.com/crypto-power/cryptopower/ui/page/components.(*WalletAndAccountSelector).SetSelectedAsset(0x0?, {0xc004d9e740?, 0x1?, 0xc0086b8e50?})
        /Users/philemon/Desktop/osp/cryptopower/ui/page/components/wallet_account_selector.go:145 +0x1d
github.com/crypto-power/cryptopower/ui/page/exchange.(*CreateOrderPage).updateAssetSelection(0xc000270000, {0xc00064bd10, 0xc0086b8e01?, 0xc005970a80?}, {0x0, 0x0, 0x100cac9e6?})
        /Users/philemon/Desktop/osp/cryptopower/ui/page/exchange/create_order_page.go:463 +0xef
github.com/crypto-power/cryptopower/ui/page/exchange.(*CreateOrderPage).updateWalletAndAccountSelector(0xc002c89040?, {0xc00064bd10?, 0x10004acb3?, 0x10003b036?}, {0x0?, 0xc00328f068?, 0x100cac9c0?})
        /Users/philemon/Desktop/osp/cryptopower/ui/page/exchange/create_order_page.go:210 +0x28
github.com/crypto-power/cryptopower/ui/page/exchange.NewCreateOrderPage.func1(0xc005972040)
        /Users/philemon/Desktop/osp/cryptopower/ui/page/exchange/create_order_page.go:171 +0x116
github.com/crypto-power/cryptopower/ui/page/components.NewAssetTypeSelector.func1(0xc00330acc0?)
        /Users/philemon/Desktop/osp/cryptopower/ui/page/components/asset_selector.go:68 +0x9d
github.com/crypto-power/cryptopower/ui/page/components.(*assetTypeModal).Handle(0xc005970a80)
        /Users/philemon/Desktop/osp/cryptopower/ui/page/components/asset_selector.go:234 +0x127
github.com/crypto-power/cryptopower/ui.(*Window).handleFrameEvent(0xc000392140, {{0xc142b3a5241b0ea8, 0xd472f80a4, 0x102758220}, {0x40000000, 0x40000000}, {0x640, 0x514}, {0x0, 0x0, ...}, ...})
        /Users/philemon/Desktop/osp/cryptopower/ui/window.go:235 +0x171
github.com/crypto-power/cryptopower/ui.(*Window).HandleEvents(0xc000392140)
        /Users/philemon/Desktop/osp/cryptopower/ui/window.go:206 +0x2b9
main.main.func3()
        /Users/philemon/Desktop/osp/cryptopower/main.go:110 +0x1d
created by main.main
        /Users/philemon/Desktop/osp/cryptopower/main.go:108 +0x54e

```

### PR DESCRIPTION
**Pull request by ukane-philemon**
This MR fixes an issue that caused a panic on the create order page due to its uninitialized state after OnNavigatedTo() has been executed but before the page overlay is removed.

This issue might affect other pages that require special initialization and use an overlay.
EDIT: After a brief check, it seems no other page is affected.

Closes #183

### CODE REVIEW

File: ui/page/exchange/create_order_page.go [hunk 1]
```diff
@@ -610,6 +617,10 @@ func (pg *CreateOrderPage) Layout(gtx C) D {
 		overlaySet = true
 	}
 
+	if !overlaySet && !pg.inited {
+		pg.initPage()
+	}
```
Comment (Sirmorrison) [inline ui/page/exchange/create_order_page.go:622]: This will always be false because you are sett `pg.inited` to true in the `OnNavigatedTo()` and i dont see any where it is set back to false.

Comment (ukane-philemon) [reply ui/page/exchange/create_order_page.go:622]: We need to execute this once. If the page was already in the stack, we never run OnNavigatedTo() which does the first init.

Comment (Sirmorrison) [reply ui/page/exchange/create_order_page.go:622]: When ever a page is navigated to, the `OnNavigatedTo()` is always called the last time i checked. if the plan is to only initialise this once, i will recommend moving it to the `NewCreateOrderPage()`

Comment (ukane-philemon) [reply ui/page/exchange/create_order_page.go:622]: > When ever a page is navigated to, the `OnNavigatedTo()` is always called the last time i checked. if the plan is to only initialise this once, i will recommend moving it to the `NewCreateOrderPage()`

Not really. For example navigating to the create order view will execute OnNavigatedTo the first time but won’t when we visit the general setting view from there and use the back arrow icon on the settings page.

**Comment by Sirmorrison** [comment]
```
panic: runtime error: index out of range [0] with length 0

goroutine 30 [running]:
github.com/crypto-power/cryptopower/ui/page/components.(*WalletAndAccountSelector).SetSelectedAsset(0xc0000fe0c0, {0xc004b1e9a0?, 0x0?, 0x1?})
	/Users/apple/Desktop/cryptopower/cryptopower/ui/page/components/wallet_account_selector.go:147 +0xfd
github.com/crypto-power/cryptopower/ui/page/exchange.(*CreateOrderPage).updateAssetSelection(0xc006eb6c00, {0xc002afdd10, 0xc00625e601?, 0xc0031f3c00?}, {0x0, 0x0, 0x100c90906?})
	/Users/apple/Desktop/cryptopower/cryptopower/ui/page/exchange/create_order_page.go:474 +0xef
github.com/crypto-power/cryptopower/ui/page/exchange.(*CreateOrderPage).updateWalletAndAccountSelector(0xc0005831e0?, {0xc002afdd10?, 0x10004d0b3?, 0x10003dbd6?}, {0x0?, 0xc0030feb98?, 0x100c908e0?})
	/Users/apple/Desktop/cryptopower/cryptopower/ui/page/exchange/create_order_page.go:211 +0x28
github.com/crypto-power/cryptopower/ui/page/exchange.NewCreateOrderPage.func1(0xc0001037a0)
	/Users/apple/Desktop/cryptopower/cryptopower/ui/page/exchange/create_order_page.go:172 +0x116
github.com/crypto-power/cryptopower/ui/page/components.NewAssetTypeSelector.func1(0xc0001037a0?)
	/Users/apple/Desktop/cryptopower/cryptopower/ui/page/components/asset_selector.go:68 +0x9d
github.com/crypto-power/cryptopower/ui/page/components.(*assetTypeModal).Handle(0xc0031f3c00)
	/Users/apple/Desktop/cryptopower/cryptopower/ui/page/components/asset_selector.go:234 +0x127
github.com/crypto-power/cryptopower/ui.(*Window).handleFrameEvent(0xc002e200a0, {{0xc1445298e40f1c10, 0x2bcb04e4f, 0x102727fc0}, {0x40000000, 0x40000000}, {0x640, 0x514}, {0x0, 0x0, ...}, ...})
	/Users/apple/Desktop/cryptopower/cryptopower/ui/window.go:235 +0x171
github.com/crypto-power/cryptopower/ui.(*Window).HandleEvents(0xc002e200a0)
	/Users/apple/Desktop/cryptopower/cryptopower/ui/window.go:206 +0x2b6
main.main.func3()
	/Users/apple/Desktop/cryptopower/cryptopower/main.go:110 +0x1d
created by main.main
	/Users/apple/Desktop/cryptopower/cryptopower/main.go:108 +0x553
```
The app crashes when i select an asset i currently don't have example: i only have BTC and DCR.. selecting LTC, the app will crash.

**Comment by ukane-philemon** [comment]
Is this reproducible on master?

**Comment by dreacot** [comment]
> Is this reproducible on master?
> 
> Edit: This panic is reproducible on master but I'll sneak in a fix cuz it's related. @Sirmorrison, @dreacot, what do you think would be a correct behaviour when the wallet for a swap asset does not exist yet?

please create a follow up issue for this @ukane-philemon

**Review by dreacot — APPROVED** [review]

**Comment by Sirmorrison** [comment]
> overlaySet

so if the wallet selector is able to take asset types as parameters, it would be ideal to pass the asset types of the users wallets to the wallet selector. That way, only available assets are displayed on  the selector.
