### PR TITLE
Allow sending to multiple recipients and fix some bugs

### LINKED ISSUE #42: allow sending to multiple recipients

### LINKED ISSUE #380: switching from address to wallet selects the same btc wallet and account, the account shouldn't be the same by default
image

### LINKED ISSUE #407: After Clicking on "Get Tickets Now", The back button on the wallet page doesn't work
After Clicking on "Get Tickets Now"

Image

The back button on the wallet page doesn't work
Image

### PR DESCRIPTION
**Pull request by JustinBeBoy**
Resolve #380 
Resolve #407 
Resolve #42

### CODE REVIEW

File: ui/page/send/page.go [hunk 1]
```diff
@@ -186,31 +215,22 @@ func (pg *Page) initializeAccountSelectors() {
...
 	}
-
-	pg.recipient.initializeAccountSelectors(pg.sourceAccountSelector.SelectedAccount())
 }
 
 // RestyleWidgets restyles select widgets to match the current theme. This is
 // especially necessary when the dark mode setting is changed.
 func (pg *Page) RestyleWidgets() {
-	pg.recipient.restyleWidgets()
+	// pg.recipient.restyleWidgets()
```
Comment (dreacot) [inline ui/page/send/page.go:233]: should this be uncommented?

File: ui/page/send/page.go [hunk 2]
```diff
@@ -333,75 +337,200 @@ func (pg *Page) constructTx() {
...
-	if SendMax {
-		// TODO: this workaround ignores the change events from the
-		// amount input to avoid construct tx cycle.
-		pg.recipient.setAmount(amountAtom)
-	}
+	// if SendMax {
+	// TODO: this workaround ignores the change events from the
+	// amount input to avoid construct tx cycle.
+	// 	pg.recipient.setAmount(amountAtom)
+	// }
```
Comment (dreacot) [inline ui/page/send/page.go:377]: why is this commented?

File: ui/page/send/page.go [hunk 3]
```diff
@@ -468,10 +597,15 @@ func (pg *Page) HandleUserInteractions() {
 		if pg.selectedWallet.IsUnsignedTxExist() {
 			pg.confirmTxModal = newSendConfirmModal(pg.Load, pg.authoredTxData, pg.selectedWallet)
 			pg.confirmTxModal.exchangeRateSet = pg.exchangeRate != -1 && pg.usdExchangeSet
-			pg.confirmTxModal.txLabel = pg.recipient.descriptionText()
-
+			// TODO handle if have many descryption text
+			// this workaround to show description text when have one recipient and don't show when have more
```
Comment (dreacot) [inline ui/page/send/page.go:601]:
```suggestion
			// TODO handle if there are many description texts
			// this workaround shows the description text when there is only one recipient and does not show when have more than one recipient
```

**Review by dreacot — CHANGES_REQUESTED** [review]

**Review by dreacot — APPROVED** [review]
